[package]
name = "nifti_processing"
version = "0.1.2"
edition = "2021"
description = "nibabel like 3d resampling functions for Nifti-rs"
readme = "README.md"
repository = "https://github.com/liob/NIFTI-Processing-rs"
authors = ["Hinrich Winther <hbwinther@gmail.com>"]
license = "MIT OR Apache-2.0"
keywords = ["nifti", "imaging", "3d", "resampling", "nibabel"]


[dependencies]
nalgebra   = { version = "0.32", default-features = false, features = ["std"] }
ndarray    = { version = "0.16", default-features = false }
itertools  = "0.10"
num-traits = { version = "0.2",  default-features = false }
rayon      = { version = "1.6" }

[dev-dependencies]
nifti  = { version = "0.15.0", features = ["nalgebra_affine"] }
# tqdm
kdam   = "0.3.0"
# command line parameters
clap   = { version = "4.0", features = ["derive"] }
approx = { version = "0.5", default-features = false }
criterion = "0.5"

[[bench]]
name = "speed_benchmark"
harness = false
